image: python:3.9

pipelines:
  pull-requests:
    "**":
      - step:
          name: Lint
          script:
            - echo "Running linter..."
            - python -m pip install uv
            - uv venv
            - . .venv/bin/activate
            - make ruff
          after-script:
            - if [ $BITBUCKET_EXIT_CODE -ne 0 ]; then echo "Lint failed. PR will be declined."; exit 1; fi
      - step:
          name: Test
          script:
            - echo "Running build and tests..."
            - python -m pip install uv
            - uv venv
            - . .venv/bin/activate
            - make install
            - make coverage
          after-script:
            - if [ $BITBUCKET_EXIT_CODE -ne 0 ]; then echo "Build and Test failed. PR will be declined."; exit 1; fi

  branches:
    main:
      - step:
          name: Increment Patch Version
          script:
            - chmod +x semver.sh
            - ./semver.sh
      - step:
          name: Test
          script:
            - echo "Running build and tests..."
            - python -m pip install uv
            - uv venv
            - . .venv/bin/activate
            - make install
            - make coverage
