name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install uv
        run: python -m pip install uv
      - name: Create venv
        run: uv venv
      - name: Activate venv and run linter
        run: |
          . .venv/bin/activate
          make ruff

  test:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install uv
        run: python -m pip install uv
      - name: Create venv
        run: uv venv
      - name: Activate venv, install, and test
        run: |
          . .venv/bin/activate
          make install
          make coverage

  semver:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make semver.sh executable
        run: chmod +x semver.sh
      - name: Run semver.sh
        run: ./semver.sh
